/* Baja California Sur land polygon for the quiz map.
 *
 * Source: Natural Earth 10m physical land (public domain).
 *
 * The naive approach — keep every vertex inside a bounding box — is wrong,
 * because Baja is joined to mainland Mexico, so the ring containing Los Cabos
 * is the whole continent. Filtering its points leaves an open path, and
 * closing that with Z draws a chord across the Pacific and fills the sea.
 *
 * Sutherland–Hodgman clips the ring against the frame rectangle instead,
 * walking each edge and inserting the true crossing points. The result is a
 * genuinely closed polygon whose interior is land.
 */
const fs = require("fs");

const FRAME = { W: -111.35, E: -108.75, S: 22.55, N: 24.75 };

const inside = (p, edge) =>
  edge === "W" ? p[0] >= FRAME.W
  : edge === "E" ? p[0] <= FRAME.E
  : edge === "S" ? p[1] >= FRAME.S
  : p[1] <= FRAME.N;

function intersect(a, b, edge) {
  const [x1, y1] = a, [x2, y2] = b;
  if (edge === "W" || edge === "E") {
    const x = edge === "W" ? FRAME.W : FRAME.E;
    return [x, y1 + ((y2 - y1) * (x - x1)) / (x2 - x1)];
  }
  const y = edge === "S" ? FRAME.S : FRAME.N;
  return [x1 + ((x2 - x1) * (y - y1)) / (y2 - y1), y];
}

function clip(poly, edge) {
  const out = [];
  for (let i = 0; i < poly.length; i++) {
    const cur = poly[i], prev = poly[(i + poly.length - 1) % poly.length];
    const curIn = inside(cur, edge), prevIn = inside(prev, edge);
    if (curIn) {
      if (!prevIn) out.push(intersect(prev, cur, edge));
      out.push(cur);
    } else if (prevIn) {
      out.push(intersect(prev, cur, edge));
    }
  }
  return out;
}

const g = JSON.parse(fs.readFileSync(process.argv[2] || "/tmp/ne10.json", "utf8"));
let ring = null;
for (const f of g.features || []) {
  const geom = f.geometry; if (!geom) continue;
  const polys = geom.type === "Polygon" ? [geom.coordinates]
    : geom.type === "MultiPolygon" ? geom.coordinates : [];
  for (const poly of polys) {
    const r = poly[0];
    const hits = r.filter(([x, y]) => x >= FRAME.W && x <= FRAME.E && y >= FRAME.S && y <= FRAME.N);
    if (hits.length > 40 && (!ring || r.length > ring.length)) ring = r;
  }
}
if (!ring) { console.error("no ring found in frame"); process.exit(1); }
console.log("source ring points:", ring.length);

let poly = ring;
for (const edge of ["W", "E", "S", "N"]) poly = clip(poly, edge);
console.log("after clipping:", poly.length);

const pts = poly.map(([x, y]) => [+x.toFixed(4), +y.toFixed(4)]);
const header =
  "/* AUTO-GENERATED by scripts/gen-coast.js from Natural Earth 10m land (public\n" +
  "   domain). Sutherland-Hodgman clip of the continent ring to the Los Cabos\n" +
  "   frame, so the polygon closes around LAND and the fill is the peninsula. */\n";
fs.writeFileSync("src/data/baja-coast.ts",
  header + "export const BAJA_COAST: [number, number][] = " + JSON.stringify(pts) + ";\n");
console.log("wrote", pts.length, "points,", (JSON.stringify(pts).length / 1024).toFixed(1) + "KB");
